/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * VSCode static command line definition file
 */
export interface HttpsRawGithubusercontentComLucashootenVscodeSchemasForTypescriptMainSchemasArgvJson {
  /**
   * The display Language to use. Picking a different language requires the associated language pack to be installed.
   */
  locale?: string;
  /**
   * Disables hardware acceleration. ONLY change this option if you encounter graphic issues.
   */
  "disable-hardware-acceleration"?: boolean;
  "force-color-profile"?: string;
  "enable-crash-reporter"?: boolean;
  "crash-reporter-id"?: string;
  /**
   * Enable proposed APIs for a list of extension ids (such as `vscode.git`). Proposed APIs are unstable and subject to breaking without warning at any time. This should only be set for extension development and testing purposes.
   */
  "enable-proposed-api"?: string[];
  /**
   * Log level to use. Default is 'info'. Allowed values are 'error', 'warn', 'info', 'debug', 'trace', 'off'.
   */
  "log-level"?: string | unknown[];
}
