/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User snippet configuration
 */
export interface HttpsRawGithubusercontentComLucashootenVscodeSchemasForTypescriptMainSchemasGlobalSnippetsJson {
  [k: string]: {
    /**
     * The prefix to use when selecting the snippet in intellisense
     */
    prefix?: string | unknown[];
    /**
     * The snippet is meant to populate or replace a whole file
     */
    isFileTemplate?: boolean;
    body: string | string[];
    /**
     * The snippet description.
     */
    description?: string | unknown[];
    /**
     * A list of language names to which this snippet applies, e.g. 'typescript,javascript'.
     */
    scope?: string;
  };
}
