/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProductIconTheme {
  fonts?: {
    /**
     * The ID of the font.
     */
    id: string;
    /**
     * The location of the font.
     */
    src: {
      /**
       * The font path, relative to the current product icon theme file.
       */
      path: string;
      /**
       * The format of the font.
       */
      format: "woff" | "woff2" | "truetype" | "opentype" | "embedded-opentype" | "svg";
      [k: string]: unknown;
    }[];
    /**
     * The weight of the font. See https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight for valid values.
     */
    weight?: (("normal" | "bold" | "lighter" | "bolder") | string) & string;
    /**
     * The style of the font. See https://developer.mozilla.org/en-US/docs/Web/CSS/font-style for valid values.
     */
    style?: (("normal" | "italic" | "oblique") | string) & string;
    [k: string]: unknown;
  }[];
  iconDefinitions?: Icons;
  [k: string]: unknown;
}
/**
 * Association of icon name to a font character.
 */
export interface Icons {
  add?: Icons1;
  plus?: Icons1;
  "gist-new"?: Icons1;
  "repo-create"?: Icons1;
  lightbulb?: Icons1;
  "light-bulb"?: Icons1;
  repo?: Icons1;
  "repo-delete"?: Icons1;
  "gist-fork"?: Icons1;
  "repo-forked"?: Icons1;
  "git-pull-request"?: Icons1;
  "git-pull-request-abandoned"?: Icons1;
  "record-keys"?: Icons1;
  keyboard?: Icons1;
  tag?: Icons1;
  "tag-add"?: Icons1;
  "tag-remove"?: Icons1;
  person?: Icons1;
  "person-follow"?: Icons1;
  "person-outline"?: Icons1;
  "person-filled"?: Icons1;
  "git-branch"?: Icons1;
  "git-branch-create"?: Icons1;
  "git-branch-delete"?: Icons1;
  "source-control"?: Icons1;
  mirror?: Icons1;
  "mirror-public"?: Icons1;
  star?: Icons1;
  "star-add"?: Icons1;
  "star-delete"?: Icons1;
  "star-empty"?: Icons1;
  comment?: Icons1;
  "comment-add"?: Icons1;
  alert?: Icons1;
  warning?: Icons1;
  search?: Icons1;
  "search-save"?: Icons1;
  "log-out"?: Icons1;
  "sign-out"?: Icons1;
  "log-in"?: Icons1;
  "sign-in"?: Icons1;
  eye?: Icons1;
  "eye-unwatch"?: Icons1;
  "eye-watch"?: Icons1;
  "circle-filled"?: Icons1;
  "primitive-dot"?: Icons1;
  "close-dirty"?: Icons1;
  "debug-breakpoint"?: Icons2;
  "debug-breakpoint-disabled"?: Icons3;
  "debug-hint"?: Icons4;
  "primitive-square"?: Icons1;
  edit?: Icons1;
  pencil?: Icons1;
  info?: Icons1;
  "issue-opened"?: Icons1;
  "gist-private"?: Icons1;
  "git-fork-private"?: Icons1;
  lock?: Icons1;
  "mirror-private"?: Icons1;
  close?: Icons1;
  "remove-close"?: Icons1;
  x?: Icons1;
  "repo-sync"?: Icons1;
  sync?: Icons1;
  clone?: Icons1;
  "desktop-download"?: Icons1;
  beaker?: Icons1;
  microscope?: Icons1;
  vm?: Icons1;
  "device-desktop"?: Icons1;
  file?: Icons1;
  "file-text"?: Icons1;
  more?: Icons1;
  ellipsis?: Icons1;
  "kebab-horizontal"?: Icons1;
  "mail-reply"?: Icons1;
  reply?: Icons1;
  organization?: Icons1;
  "organization-filled"?: Icons1;
  "organization-outline"?: Icons1;
  "new-file"?: Icons1;
  "file-add"?: Icons1;
  "new-folder"?: Icons1;
  "file-directory-create"?: Icons1;
  trash?: Icons1;
  trashcan?: Icons1;
  history?: Icons1;
  clock?: Icons1;
  folder?: Icons1;
  "file-directory"?: Icons1;
  "symbol-folder"?: Icons1;
  "logo-github"?: Icons1;
  "mark-github"?: Icons1;
  github?: Icons1;
  terminal?: Icons1;
  console?: Icons1;
  repl?: Icons1;
  zap?: Icons1;
  "symbol-event"?: Icons1;
  error?: Icons1;
  stop?: Icons1;
  variable?: Icons1;
  "symbol-variable"?: Icons1;
  array?: Icons1;
  "symbol-array"?: Icons1;
  "symbol-module"?: Icons1;
  "symbol-package"?: Icons1;
  "symbol-namespace"?: Icons1;
  "symbol-object"?: Icons1;
  "symbol-method"?: Icons1;
  "symbol-function"?: Icons1;
  "symbol-constructor"?: Icons1;
  "symbol-boolean"?: Icons1;
  "symbol-null"?: Icons1;
  "symbol-numeric"?: Icons1;
  "symbol-number"?: Icons1;
  "symbol-structure"?: Icons1;
  "symbol-struct"?: Icons1;
  "symbol-parameter"?: Icons1;
  "symbol-type-parameter"?: Icons1;
  "symbol-key"?: Icons1;
  "symbol-text"?: Icons1;
  "symbol-reference"?: Icons1;
  "go-to-file"?: Icons1;
  "symbol-enum"?: Icons1;
  "symbol-value"?: Icons1;
  "symbol-ruler"?: Icons1;
  "symbol-unit"?: Icons1;
  "activate-breakpoints"?: Icons1;
  archive?: Icons1;
  "arrow-both"?: Icons1;
  "arrow-down"?: Icons1;
  "arrow-left"?: Icons1;
  "arrow-right"?: Icons1;
  "arrow-small-down"?: Icons1;
  "arrow-small-left"?: Icons1;
  "arrow-small-right"?: Icons1;
  "arrow-small-up"?: Icons1;
  "arrow-up"?: Icons1;
  bell?: Icons1;
  bold?: Icons1;
  book?: Icons1;
  bookmark?: Icons1;
  "debug-breakpoint-conditional-unverified"?: Icons5;
  "debug-breakpoint-conditional"?: Icons6;
  "debug-breakpoint-conditional-disabled"?: Icons7;
  "debug-breakpoint-data-unverified"?: Icons8;
  "debug-breakpoint-data"?: Icons9;
  "debug-breakpoint-data-disabled"?: Icons10;
  "debug-breakpoint-log-unverified"?: Icons11;
  "debug-breakpoint-log"?: Icons12;
  "debug-breakpoint-log-disabled"?: Icons13;
  briefcase?: Icons1;
  broadcast?: Icons1;
  browser?: Icons1;
  bug?: Icons1;
  calendar?: Icons1;
  "case-sensitive"?: Icons1;
  check?: Icons1;
  checklist?: Icons1;
  "chevron-down"?: Icons1;
  "drop-down-button"?: Icons1;
  "chevron-left"?: Icons1;
  "chevron-right"?: Icons1;
  "chevron-up"?: Icons1;
  "chrome-close"?: Icons1;
  "chrome-maximize"?: Icons1;
  "chrome-minimize"?: Icons1;
  "chrome-restore"?: Icons1;
  circle?: Icons1;
  "circle-outline"?: Icons1;
  "debug-breakpoint-unverified"?: Icons14;
  "circle-slash"?: Icons1;
  "circuit-board"?: Icons1;
  "clear-all"?: Icons1;
  clippy?: Icons1;
  "close-all"?: Icons1;
  "cloud-download"?: Icons1;
  "cloud-upload"?: Icons1;
  code?: Icons1;
  "collapse-all"?: Icons1;
  "color-mode"?: Icons1;
  "comment-discussion"?: Icons1;
  "compare-changes"?: Icons1;
  "credit-card"?: Icons1;
  dash?: Icons1;
  dashboard?: Icons1;
  database?: Icons1;
  "debug-continue"?: Icons15;
  "debug-disconnect"?: Icons16;
  "debug-pause"?: Icons17;
  "debug-restart"?: Icons18;
  "debug-start"?: Icons19;
  "debug-step-into"?: Icons20;
  "debug-step-out"?: Icons21;
  "debug-step-over"?: Icons22;
  "debug-stop"?: Icons23;
  debug?: Icons1;
  "device-camera-video"?: Icons1;
  "device-camera"?: Icons1;
  "device-mobile"?: Icons1;
  "diff-added"?: Icons1;
  "diff-ignored"?: Icons1;
  "diff-modified"?: Icons1;
  "diff-removed"?: Icons1;
  "diff-renamed"?: Icons1;
  diff?: Icons1;
  discard?: Icons1;
  "editor-layout"?: Icons1;
  "empty-window"?: Icons1;
  exclude?: Icons1;
  extensions?: Icons1;
  "eye-closed"?: Icons1;
  "file-binary"?: Icons1;
  "file-code"?: Icons1;
  "file-media"?: Icons1;
  "file-pdf"?: Icons1;
  "file-submodule"?: Icons1;
  "file-symlink-directory"?: Icons1;
  "file-symlink-file"?: Icons1;
  "file-zip"?: Icons1;
  files?: Icons1;
  filter?: Icons1;
  flame?: Icons1;
  "fold-down"?: Icons1;
  "fold-up"?: Icons1;
  fold?: Icons1;
  "folder-active"?: Icons1;
  "folder-opened"?: Icons1;
  gear?: Icons1;
  gift?: Icons1;
  "gist-secret"?: Icons1;
  gist?: Icons1;
  "git-commit"?: Icons1;
  "git-compare"?: Icons1;
  "git-merge"?: Icons1;
  "github-action"?: Icons1;
  "github-alt"?: Icons1;
  globe?: Icons1;
  grabber?: Icons1;
  graph?: Icons1;
  gripper?: Icons1;
  heart?: Icons1;
  home?: Icons1;
  "horizontal-rule"?: Icons1;
  hubot?: Icons1;
  inbox?: Icons1;
  "issue-closed"?: Icons1;
  "issue-reopened"?: Icons1;
  issues?: Icons1;
  italic?: Icons1;
  jersey?: Icons1;
  json?: Icons1;
  bracket?: Icons1;
  "kebab-vertical"?: Icons1;
  key?: Icons1;
  law?: Icons1;
  "lightbulb-autofix"?: Icons1;
  "link-external"?: Icons1;
  link?: Icons1;
  "list-ordered"?: Icons1;
  "list-unordered"?: Icons1;
  "live-share"?: Icons1;
  loading?: Icons1;
  location?: Icons1;
  "mail-read"?: Icons1;
  mail?: Icons1;
  markdown?: Icons1;
  megaphone?: Icons1;
  mention?: Icons1;
  milestone?: Icons1;
  "mortar-board"?: Icons1;
  move?: Icons1;
  "multiple-windows"?: Icons1;
  mute?: Icons1;
  "no-newline"?: Icons1;
  note?: Icons1;
  octoface?: Icons1;
  "open-preview"?: Icons1;
  package?: Icons1;
  paintcan?: Icons1;
  pin?: Icons1;
  play?: Icons1;
  run?: Icons1;
  plug?: Icons1;
  "preserve-case"?: Icons1;
  preview?: Icons1;
  project?: Icons1;
  pulse?: Icons1;
  question?: Icons1;
  quote?: Icons1;
  "radio-tower"?: Icons1;
  reactions?: Icons1;
  references?: Icons1;
  refresh?: Icons1;
  regex?: Icons1;
  "remote-explorer"?: Icons1;
  remote?: Icons1;
  remove?: Icons1;
  "replace-all"?: Icons1;
  replace?: Icons1;
  "repo-clone"?: Icons1;
  "repo-force-push"?: Icons1;
  "repo-pull"?: Icons1;
  "repo-push"?: Icons1;
  report?: Icons1;
  "request-changes"?: Icons1;
  rocket?: Icons1;
  "root-folder-opened"?: Icons1;
  "root-folder"?: Icons1;
  rss?: Icons1;
  ruby?: Icons1;
  "save-all"?: Icons1;
  "save-as"?: Icons1;
  save?: Icons1;
  "screen-full"?: Icons1;
  "screen-normal"?: Icons1;
  "search-stop"?: Icons24;
  server?: Icons1;
  "settings-gear"?: Icons1;
  settings?: Icons1;
  shield?: Icons1;
  smiley?: Icons1;
  "sort-precedence"?: Icons1;
  "split-horizontal"?: Icons1;
  "split-vertical"?: Icons1;
  squirrel?: Icons1;
  "star-full"?: Icons1;
  "star-half"?: Icons1;
  "symbol-class"?: Icons1;
  "symbol-color"?: Icons1;
  "symbol-customcolor"?: Icons1;
  "symbol-constant"?: Icons1;
  "symbol-enum-member"?: Icons1;
  "symbol-field"?: Icons1;
  "symbol-file"?: Icons1;
  "symbol-interface"?: Icons1;
  "symbol-keyword"?: Icons1;
  "symbol-misc"?: Icons1;
  "symbol-operator"?: Icons1;
  "symbol-property"?: Icons1;
  wrench?: Icons1;
  "wrench-subaction"?: Icons1;
  "symbol-snippet"?: Icons1;
  tasklist?: Icons1;
  telescope?: Icons1;
  "text-size"?: Icons1;
  "three-bars"?: Icons1;
  thumbsdown?: Icons1;
  thumbsup?: Icons1;
  tools?: Icons1;
  "triangle-down"?: Icons1;
  "triangle-left"?: Icons1;
  "triangle-right"?: Icons1;
  "triangle-up"?: Icons1;
  twitter?: Icons1;
  unfold?: Icons1;
  unlock?: Icons1;
  unmute?: Icons1;
  unverified?: Icons1;
  verified?: Icons1;
  versions?: Icons1;
  "vm-active"?: Icons1;
  "vm-outline"?: Icons1;
  "vm-running"?: Icons1;
  watch?: Icons1;
  whitespace?: Icons1;
  "whole-word"?: Icons1;
  window?: Icons1;
  "word-wrap"?: Icons1;
  "zoom-in"?: Icons1;
  "zoom-out"?: Icons1;
  "list-filter"?: Icons1;
  "list-flat"?: Icons1;
  "list-selection"?: Icons1;
  selection?: Icons1;
  "list-tree"?: Icons1;
  "debug-breakpoint-function-unverified"?: Icons25;
  "debug-breakpoint-function"?: Icons26;
  "debug-breakpoint-function-disabled"?: Icons27;
  "debug-stackframe-active"?: Icons1;
  "circle-small-filled"?: Icons1;
  "debug-stackframe-dot"?: Icons1;
  "debug-stackframe"?: Icons28;
  "debug-stackframe-focused"?: Icons29;
  "debug-breakpoint-unsupported"?: Icons30;
  "symbol-string"?: Icons1;
  "debug-reverse-continue"?: Icons31;
  "debug-step-back"?: Icons32;
  "debug-restart-frame"?: Icons33;
  "call-incoming"?: Icons1;
  "call-outgoing"?: Icons1;
  menu?: Icons1;
  "expand-all"?: Icons1;
  feedback?: Icons1;
  "group-by-ref-type"?: Icons1;
  "ungroup-by-ref-type"?: Icons1;
  account?: Icons1;
  "bell-dot"?: Icons1;
  "debug-console"?: Icons34;
  library?: Icons1;
  output?: Icons1;
  "run-all"?: Icons1;
  "sync-ignored"?: Icons1;
  pinned?: Icons1;
  "github-inverted"?: Icons1;
  "debug-alt"?: Icons1;
  "server-process"?: Icons1;
  "server-environment"?: Icons1;
  pass?: Icons1;
  "stop-circle"?: Icons1;
  "play-circle"?: Icons1;
  record?: Icons1;
  "debug-alt-small"?: Icons1;
  "vm-connect"?: Icons1;
  cloud?: Icons1;
  merge?: Icons1;
  export?: Icons1;
  "graph-left"?: Icons1;
  magnet?: Icons1;
  notebook?: Icons1;
  redo?: Icons1;
  "check-all"?: Icons1;
  "pinned-dirty"?: Icons1;
  "pass-filled"?: Icons1;
  "circle-large-filled"?: Icons1;
  "circle-large"?: Icons1;
  "circle-large-outline"?: Icons1;
  combine?: Icons1;
  gather?: Icons1;
  table?: Icons1;
  "variable-group"?: Icons1;
  "type-hierarchy"?: Icons1;
  "type-hierarchy-sub"?: Icons1;
  "type-hierarchy-super"?: Icons1;
  "git-pull-request-create"?: Icons1;
  "run-above"?: Icons1;
  "run-below"?: Icons1;
  "notebook-template"?: Icons1;
  "debug-rerun"?: Icons1;
  "workspace-trusted"?: Icons1;
  "workspace-untrusted"?: Icons1;
  "workspace-unspecified"?: Icons1;
  "terminal-cmd"?: Icons1;
  "terminal-debian"?: Icons1;
  "terminal-linux"?: Icons1;
  "terminal-powershell"?: Icons1;
  "terminal-tmux"?: Icons1;
  "terminal-ubuntu"?: Icons1;
  "terminal-bash"?: Icons1;
  "arrow-swap"?: Icons1;
  copy?: Icons1;
  "person-add"?: Icons1;
  "filter-filled"?: Icons1;
  wand?: Icons1;
  "debug-line-by-line"?: Icons1;
  inspect?: Icons1;
  layers?: Icons1;
  "layers-dot"?: Icons1;
  "layers-active"?: Icons1;
  compass?: Icons1;
  "compass-dot"?: Icons1;
  "compass-active"?: Icons1;
  azure?: Icons1;
  "issue-draft"?: Icons1;
  "git-pull-request-closed"?: Icons1;
  "git-pull-request-draft"?: Icons1;
  "debug-all"?: Icons1;
  "debug-coverage"?: Icons1;
  "run-errors"?: Icons1;
  "folder-library"?: Icons1;
  "debug-continue-small"?: Icons1;
  "beaker-stop"?: Icons1;
  "graph-line"?: Icons1;
  "graph-scatter"?: Icons1;
  "pie-chart"?: Icons1;
  "bracket-dot"?: Icons1;
  "bracket-error"?: Icons1;
  "lock-small"?: Icons1;
  "azure-devops"?: Icons1;
  "verified-filled"?: Icons1;
  newline?: Icons1;
  layout?: Icons1;
  "layout-activitybar-left"?: Icons1;
  "layout-activitybar-right"?: Icons1;
  "layout-panel-left"?: Icons1;
  "layout-panel-center"?: Icons1;
  "layout-panel-justify"?: Icons1;
  "layout-panel-right"?: Icons1;
  "layout-panel"?: Icons1;
  "layout-sidebar-left"?: Icons1;
  "layout-sidebar-right"?: Icons1;
  "layout-statusbar"?: Icons1;
  "layout-menubar"?: Icons1;
  "layout-centered"?: Icons1;
  "layout-sidebar-right-off"?: Icons1;
  "layout-panel-off"?: Icons1;
  "layout-sidebar-left-off"?: Icons1;
  target?: Icons1;
  indent?: Icons1;
  "record-small"?: Icons1;
  "error-small"?: Icons1;
  "arrow-circle-down"?: Icons1;
  "arrow-circle-left"?: Icons1;
  "arrow-circle-right"?: Icons1;
  "arrow-circle-up"?: Icons1;
  "heart-filled"?: Icons1;
  map?: Icons1;
  "map-filled"?: Icons1;
  "circle-small"?: Icons1;
  "bell-slash"?: Icons1;
  "bell-slash-dot"?: Icons1;
  "comment-unresolved"?: Icons1;
  "git-pull-request-go-to-changes"?: Icons1;
  "git-pull-request-new-changes"?: Icons1;
  "search-fuzzy"?: Icons1;
  "comment-draft"?: Icons1;
  "dialog-error"?: Icons1;
  "dialog-warning"?: Icons1;
  "dialog-info"?: Icons1;
  "dialog-close"?: Icons1;
  "tree-item-expanded"?: Icons1;
  "tree-filter-on-type-on"?: Icons1;
  "tree-filter-on-type-off"?: Icons1;
  "tree-filter-clear"?: Icons1;
  "tree-item-loading"?: Icons1;
  "menu-selection"?: Icons1;
  "menu-submenu"?: Icons1;
  "menubar-more"?: Icons1;
  "scrollbar-button-left"?: Icons1;
  "scrollbar-button-right"?: Icons1;
  "scrollbar-button-up"?: Icons1;
  "scrollbar-button-down"?: Icons1;
  "toolbar-more"?: Icons1;
  "quick-input-back"?: Icons1;
  "widget-close"?: Icons35;
  "goto-previous-location"?: Icons36;
  "goto-next-location"?: Icons37;
  "diff-review-insert"?: Icons38;
  "diff-review-remove"?: Icons39;
  "diff-review-close"?: Icons40;
  "parameter-hints-next"?: Icons41;
  "parameter-hints-previous"?: Icons42;
  "suggest-more-info"?: Icons43;
  "diff-insert"?: Icons44;
  "diff-remove"?: Icons45;
  "find-selection"?: Icons46;
  "find-collapsed"?: Icons47;
  "find-expanded"?: Icons48;
  "find-replace"?: Icons49;
  "find-replace-all"?: Icons50;
  "find-previous-match"?: Icons51;
  "find-next-match"?: Icons52;
  "folding-expanded"?: Icons53;
  "folding-collapsed"?: Icons54;
  "folding-manual-collapsed"?: Icons55;
  "folding-manual-expanded"?: Icons56;
  "marker-navigation-next"?: Icons57;
  "marker-navigation-previous"?: Icons58;
  "inline-suggestion-hints-next"?: Icons59;
  "inline-suggestion-hints-previous"?: Icons60;
  "extensions-warning-message"?: Icons61;
  "notifications-clear"?: Icons62;
  "notifications-clear-all"?: Icons63;
  "notifications-hide"?: Icons64;
  "notifications-expand"?: Icons65;
  "notifications-collapse"?: Icons66;
  "notifications-configure"?: Icons67;
  "notifications-do-not-disturb"?: Icons68;
  "default-view-icon"?: Icons69;
  "review-comment-collapse"?: Icons70;
  "debug-console-view-icon"?: Icons71;
  "run-view-icon"?: Icons72;
  "variables-view-icon"?: Icons73;
  "watch-view-icon"?: Icons74;
  "callstack-view-icon"?: Icons75;
  "breakpoints-view-icon"?: Icons76;
  "loaded-scripts-view-icon"?: Icons77;
  "debug-gripper"?: Icons78;
  "debug-run"?: Icons79;
  "debug-configure"?: Icons80;
  "debug-remove-config"?: Icons81;
  "debug-collapse-all"?: Icons82;
  "callstack-view-session"?: Icons83;
  "debug-console-clear-all"?: Icons84;
  "watch-expressions-remove-all"?: Icons85;
  "watch-expression-remove"?: Icons86;
  "watch-expressions-add"?: Icons87;
  "watch-expressions-add-function-breakpoint"?: Icons88;
  "breakpoints-remove-all"?: Icons89;
  "breakpoints-activate"?: Icons90;
  "debug-console-evaluation-input"?: Icons91;
  "debug-console-evaluation-prompt"?: Icons92;
  "debug-inspect-memory"?: Icons93;
  "edit-sessions-view-icon"?: Icons94;
  "extensions-view-icon"?: Icons95;
  "extensions-manage"?: Icons96;
  "extensions-clear-search-results"?: Icons97;
  "extensions-refresh"?: Icons98;
  "extensions-filter"?: Icons99;
  "extensions-install-local-in-remote"?: Icons100;
  "extensions-install-workspace-recommended"?: Icons101;
  "extensions-configure-recommended"?: Icons102;
  "extensions-sync-enabled"?: Icons103;
  "extensions-sync-ignored"?: Icons104;
  "extensions-remote"?: Icons105;
  "extensions-install-count"?: Icons106;
  "extensions-rating"?: Icons107;
  "extensions-verified-publisher"?: Icons108;
  "extensions-pre-release"?: Icons109;
  "extensions-sponsor"?: Icons110;
  "extensions-star-full"?: Icons111;
  "extensions-star-half"?: Icons112;
  "extensions-star-empty"?: Icons113;
  "extensions-error-message"?: Icons114;
  "extensions-info-message"?: Icons115;
  "extension-workspace-trust"?: Icons116;
  "extension-activation-time"?: Icons117;
  "localHistory-icon"?: Icons118;
  "localHistory-restore"?: Icons119;
  "find-filter"?: Icons120;
  "notebook-kernel-select"?: Icons121;
  "notebook-execute"?: Icons122;
  "notebook-execute-above"?: Icons123;
  "notebook-execute-below"?: Icons124;
  "notebook-stop"?: Icons125;
  "notebook-delete-cell"?: Icons126;
  "notebook-execute-all"?: Icons127;
  "notebook-edit"?: Icons128;
  "notebook-stop-edit"?: Icons129;
  "notebook-move-up"?: Icons130;
  "notebook-move-down"?: Icons131;
  "notebook-clear"?: Icons132;
  "notebook-split-cell"?: Icons133;
  "notebook-state-success"?: Icons134;
  "notebook-state-error"?: Icons135;
  "notebook-state-pending"?: Icons136;
  "notebook-state-executing"?: Icons137;
  "notebook-collapsed"?: Icons138;
  "notebook-expanded"?: Icons139;
  "notebook-open-as-text"?: Icons140;
  "notebook-revert"?: Icons141;
  "notebook-render-output"?: Icons142;
  "notebook-mimetype"?: Icons143;
  "notebook-diff-editor-previous-change"?: Icons144;
  "notebook-diff-editor-next-change"?: Icons145;
  "settings-folder-dropdown"?: Icons146;
  "settings-more-action"?: Icons147;
  "keybindings-record-keys"?: Icons148;
  "keybindings-sort"?: Icons149;
  "keybindings-edit"?: Icons150;
  "keybindings-add"?: Icons151;
  "settings-edit"?: Icons152;
  "settings-remove"?: Icons153;
  "settings-discard"?: Icons154;
  "preferences-clear-input"?: Icons155;
  "preferences-filter"?: Icons156;
  "preferences-open-settings"?: Icons157;
  "remote-explorer-get-started"?: Icons158;
  "remote-explorer-documentation"?: Icons159;
  "remote-explorer-feedback"?: Icons160;
  "remote-explorer-review-issues"?: Icons161;
  "remote-explorer-report-issues"?: Icons162;
  "remote-explorer-view-icon"?: Icons163;
  "ports-view-icon"?: Icons164;
  "private-ports-view-icon"?: Icons165;
  "ports-forward-icon"?: Icons166;
  "ports-stop-forward-icon"?: Icons167;
  "ports-open-browser-icon"?: Icons168;
  "ports-open-preview-icon"?: Icons169;
  "ports-copy-address-icon"?: Icons170;
  "ports-label-icon"?: Icons171;
  "ports-forwarded-without-process-icon"?: Icons172;
  "ports-forwarded-with-process-icon"?: Icons173;
  "search-details"?: Icons174;
  "search-show-context"?: Icons175;
  "search-hide-replace"?: Icons176;
  "search-show-replace"?: Icons177;
  "search-replace-all"?: Icons178;
  "search-replace"?: Icons179;
  "search-remove"?: Icons180;
  "search-refresh"?: Icons181;
  "search-collapse-results"?: Icons182;
  "search-expand-results"?: Icons183;
  "search-tree"?: Icons184;
  "search-list"?: Icons185;
  "search-clear-results"?: Icons186;
  "search-view-icon"?: Icons187;
  "search-new-editor"?: Icons188;
  "terminal-view-icon"?: Icons189;
  "terminal-rename"?: Icons190;
  "terminal-kill"?: Icons191;
  "terminal-new"?: Icons192;
  "terminal-configure-profile"?: Icons193;
  "terminal-decoration-mark"?: Icons194;
  "terminal-decoration-incomplete"?: Icons195;
  "terminal-decoration-error"?: Icons196;
  "terminal-decoration-success"?: Icons197;
  "terminal-command-history-remove"?: Icons198;
  "terminal-command-history-output"?: Icons199;
  "terminal-command-history-fuzzy-search"?: Icons200;
  "test-view-icon"?: Icons201;
  "testing-run-icon"?: Icons202;
  "testing-run-all-icon"?: Icons203;
  "testing-debug-all-icon"?: Icons204;
  "testing-debug-icon"?: Icons205;
  "testing-cancel-icon"?: Icons206;
  "testing-filter"?: Icons207;
  "testing-hidden"?: Icons208;
  "testing-show-as-list-icon"?: Icons209;
  "testing-update-profiles"?: Icons210;
  "testing-refresh-tests"?: Icons211;
  "testing-turn-continuous-run-on"?: Icons212;
  "testing-turn-continuous-run-pff"?: Icons213;
  "testing-cancel-refresh-tests"?: Icons214;
  "testing-error-icon"?: Icons215;
  "testing-failed-icon"?: Icons216;
  "testing-passed-icon"?: Icons217;
  "testing-queued-icon"?: Icons218;
  "testing-skipped-icon"?: Icons219;
  "testing-unset-icon"?: Icons220;
  "getting-started-step-unchecked"?: Icons221;
  "getting-started-step-checked"?: Icons222;
  "getting-started-setup"?: Icons223;
  "getting-started-beginner"?: Icons224;
  "getting-started-intermediate"?: Icons225;
  "callhierarchy-incoming"?: Icons226;
  "callhierarchy-outgoing"?: Icons227;
  "markers-view-multi-line-expanded"?: Icons228;
  "markers-view-multi-line-collapsed"?: Icons229;
  "tasks-list-configure"?: Icons230;
  "tasks-remove"?: Icons231;
  "auxiliarybar-right-layout-icon"?: Icons232;
  "auxiliarybar-right-off-layout-icon"?: Icons233;
  "auxiliarybar-left-layout-icon"?: Icons234;
  "auxiliarybar-left-off-layout-icon"?: Icons235;
  "view-pane-container-expanded"?: Icons236;
  "view-pane-container-collapsed"?: Icons237;
  "breadcrumb-separator"?: Icons238;
  "theme-selection-manage-extension"?: Icons239;
  "defaultProfile-icon"?: Icons240;
  "settings-sync-view-icon"?: Icons241;
  "timeline-refresh"?: Icons242;
  "timeline-pin"?: Icons243;
  "timeline-unpin"?: Icons244;
  "diff-editor-previous-change"?: Icons245;
  "diff-editor-next-change"?: Icons246;
  "diff-editor-toggle-whitespace"?: Icons247;
  "panel-maximize"?: Icons248;
  "panel-restore"?: Icons249;
  "panel-close"?: Icons250;
  "panel-layout-icon"?: Icons251;
  "panel-layout-icon-off"?: Icons252;
  menuBar?: Icons253;
  "activity-bar-left"?: Icons254;
  "activity-bar-right"?: Icons255;
  "panel-left"?: Icons256;
  "panel-left-off"?: Icons257;
  "panel-right"?: Icons258;
  "panel-right-off"?: Icons259;
  "panel-bottom"?: Icons260;
  statusBar?: Icons261;
  "panel-align-left"?: Icons262;
  "panel-align-right"?: Icons263;
  "panel-align-center"?: Icons264;
  "panel-align-justify"?: Icons265;
  fullscreen?: Icons266;
  centerLayoutIcon?: Icons267;
  zenMode?: Icons268;
  "configure-layout-icon"?: Icons269;
  "settings-view-bar-icon"?: Icons270;
  "accounts-view-bar-icon"?: Icons271;
  "comments-view-icon"?: Icons272;
  "refactor-preview-view-icon"?: Icons273;
  "explorer-view-icon"?: Icons274;
  "open-editors-view-icon"?: Icons275;
  "markers-view-icon"?: Icons276;
  "outline-view-icon"?: Icons277;
  "output-view-icon"?: Icons278;
  "source-control-view-icon"?: Icons279;
  "timeline-view-icon"?: Icons280;
  "timeline-open"?: Icons281;
  "timeline-filter"?: Icons282;
  "workspace-trust-banner"?: Icons283;
  "workspace-trust-editor-check"?: Icons284;
  "workspace-trust-editor-cross"?: Icons285;
  "workspace-trust-editor-folder-picker"?: Icons286;
  "workspace-trust-editor-edit-folder"?: Icons287;
  "workspace-trust-editor-remove-folder"?: Icons288;
  [k: string]: unknown;
}
export interface Icons1 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons2 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons3 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons4 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons5 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons6 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons7 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons8 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons9 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons10 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons11 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons12 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons13 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons14 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons15 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons16 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons17 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons18 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons19 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons20 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons21 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons22 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons23 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons24 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons25 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons26 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons27 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons28 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons29 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons30 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons31 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons32 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons33 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons34 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons35 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons36 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons37 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons38 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons39 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons40 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons41 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons42 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons43 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons44 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons45 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons46 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons47 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons48 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons49 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons50 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons51 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons52 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons53 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons54 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons55 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons56 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons57 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons58 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons59 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons60 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons61 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons62 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons63 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons64 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons65 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons66 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons67 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons68 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons69 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons70 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons71 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons72 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons73 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons74 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons75 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons76 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons77 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons78 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons79 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons80 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons81 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons82 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons83 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons84 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons85 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons86 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons87 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons88 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons89 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons90 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons91 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons92 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons93 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons94 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons95 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons96 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons97 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons98 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons99 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons100 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons101 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons102 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons103 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons104 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons105 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons106 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons107 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons108 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons109 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons110 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons111 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons112 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons113 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons114 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons115 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons116 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons117 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons118 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons119 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons120 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons121 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons122 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons123 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons124 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons125 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons126 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons127 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons128 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons129 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons130 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons131 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons132 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons133 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons134 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons135 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons136 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons137 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons138 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons139 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons140 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons141 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons142 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons143 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons144 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons145 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons146 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons147 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons148 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons149 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons150 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons151 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons152 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons153 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons154 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons155 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons156 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons157 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons158 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons159 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons160 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons161 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons162 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons163 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons164 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons165 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons166 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons167 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons168 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons169 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons170 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons171 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons172 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons173 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons174 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons175 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons176 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons177 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons178 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons179 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons180 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons181 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons182 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons183 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons184 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons185 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons186 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons187 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons188 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons189 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons190 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons191 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons192 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons193 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons194 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons195 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons196 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons197 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons198 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons199 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons200 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons201 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons202 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons203 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons204 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons205 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons206 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons207 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons208 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons209 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons210 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons211 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons212 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons213 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons214 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons215 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons216 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons217 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons218 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons219 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons220 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons221 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons222 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons223 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons224 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons225 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons226 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons227 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons228 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons229 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons230 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons231 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons232 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons233 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons234 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons235 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons236 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons237 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons238 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons239 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons240 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons241 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons242 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons243 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons244 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons245 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons246 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons247 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons248 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons249 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons250 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons251 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons252 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons253 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons254 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons255 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons256 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons257 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons258 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons259 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons260 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons261 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons262 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons263 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons264 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons265 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons266 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons267 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons268 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons269 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons270 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons271 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons272 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons273 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons274 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons275 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons276 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons277 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons278 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons279 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons280 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons281 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons282 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons283 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons284 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons285 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons286 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons287 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
export interface Icons288 {
  /**
   * The id of the font to use. If not set, the font that is defined first is used.
   */
  fontId?: string;
  /**
   * The font character associated with the icon definition.
   */
  fontCharacter?: string;
}
